// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppIcon: typeof import('./src/components/AppIcon/index.vue')['default']
    AppMenu: typeof import('./src/components/AppMenu/index.vue')['default']
    AppTable: typeof import('./src/components/AppTable/index.vue')['default']
    FileList: typeof import('./src/components/FileList/index.vue')['default']
    Loading: typeof import('./src/components/Loading/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    VanLoading: typeof import('vant/es')['Loading']
    VanOverlay: typeof import('vant/es')['Overlay']
    Verify: typeof import('./src/components/verifition/src/Verify.vue')['default']
    VerifyPoints: typeof import('./src/components/verifition/src/Verify/VerifyPoints.vue')['default']
    VerifySlide: typeof import('./src/components/verifition/src/Verify/VerifySlide.vue')['default']
  }
}
